---
title: "Chapter 6.1a Joint Probability Mass Function"
author: "Jim Albert and Monika Hu"
date: "Chapter 6 Joint Probability Distributions"
output:
#  slidy_presentation: default
  beamer_presentation: default
fontsize: 12pt
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(ggplot2)
library(ProbBayes)
library(dplyr)
library(tidyverse)
crcblue <- "#2905a1"
```

## Sampling From a Box
 
- Suppose one has a box of ten balls -- four are white, three are red, and three are black.  

- Select five balls out of the box without replacement and count the number of white and red balls in the sample.  

- What is the probability one observes two white and two red balls in the sample?
 
- We can find this probability can be found using ideas from previous chapters.
 
## Probability of 2 white and 2 red balls in sample
 
- Assume the balls are distinct and order is not important, so the total number ways of choosing 5 balls out of 10 is
 $N = {10 \choose 5} = 252.$

 - Count the number of ways of selecting two white and two red balls by selecting the white balls $({4 \choose 2}$ ways), then selecting the red balls $({3 \choose 2}$ ways), and then selecting the one remaining black ball $({3 \choose 1}$ ways).  So the total number of ways is 
 $$
 {4 \choose 2} \times {3 \choose 2} \times {3 \choose 1} = 6 \times 3 \times 3 = 54.
 $$
 
## Probability of 2 white and 2 red balls in sample

- Each one of the ${10 \choose 5} = 252$ possible outcomes of five balls is equally likely

- So the probability of choosing two white and two red balls is
 $$
 P({\rm 2 \, white \, and \, 2 \, red}) = \frac{54}{252}.
 $$
 
## Generalize calculation
 
- Suppose we want probability of choosing a specific number of white and specific number of red balls.

- We define two random variables.

 $X$ = number of red balls selected, $Y$ = number of white balls selected.
 
Based on what was found,
 $$
 P(X = 2, Y = 2) = \frac{54}{252}.
 $$
 
## Joint probability mass function

 Suppose this calculation is done for every possible pair of values of $X$ and $Y$.  The table of probabilities is given in this table.
 
 
|                   |       |        |  $Y = \# of White$      |        |       |
| :---------------: | :---: | :----: | :----: | :----: | :---: |
| \(X\) = \# of Red |   0   |   1    |   2    |   3    |   4   |
|         0         |   0   |   0    | 6/252  | 12/252 | 3/252 |
|         1         |   0   | 12/252 | 54/252 | 36/252 | 3/252 |
|         2         | 3/252 | 36/252 | 54/252 | 12/252 |   0   |
|         3         | 3/252 | 12/252 | 6/252  |   0    |   0   |

 This table is called the joint probability mass function (pmf) $f(x, y)$ of ($X, Y$). 
 
## Joint probability mass function
 
- To be a proper joint probability mass function, or joint pmf, one requires that each of the probability values are nonnegative and the sum of the probabilities over all values of $X$ and $Y$ is one.  That is,
 
1. $f(x, y) \ge 0$, for all $x$, $y$
2. $\Sigma_{x, y} f(x, y) = 1$
 
- One can check all of the probabilities in our example joint pmf are nonnegative 

- You  can confirm that the sum of the probabilities is equal to one.
 
## Back to our example

- Most likely values of $(x, y)$ are (1, 1) and (2, 1) - each has a probability of 54/252.

- Some particular pairs $(x, y)$ are not possible as $f(x, y) = 0$.  

- For example, $f(0, 1) = 0$ which means that it is not possible to observe 0 red balls and 1 white ball in the sample.  

## Finding Probabilities
 
 One finds probabilities of any event involving $X$ and $Y$ by summing probabilities over the joint pmf.

-  **What is $P(X = Y)$, the probability that one samples the same number of red and white balls?**  
- By the table, one sees that this is possible only when $X = 1, Y = 1$ or $X = 2, Y = 2$.  

- So the probability

$$
P(X = Y) = f(1, 1) + f(2, 2) = \frac{12}{252} + \frac{54}{252} = \frac{66}{252}.
$$

## Finding Probabilities

- **What is $P(X > Y)$, the probability one samples more red balls than white balls?**  

- From the table, one identifies the outcomes where $X > Y$, and then sums the corresponding probabilities.
$$
P(X > Y) = f(1, 0) + f(2, 0) + f(2, 1) + f(3, 0) 
$$

$$
+ f(3, 1) + f(3, 2) 
$$

$$
 = \frac{12}{252} + \frac{3}{252} + \frac{36}{252} + \frac{3}{252} + \frac{12}{252} + \frac{6}{252} $$
$$
 =  \frac{72}{252}
$$


 



