---
title: "Chapter 6.1c Conditional PMFs"
author: "Jim Albert and Monika Hu"
date: "Chapter 6 Joint Probability Distributions"
output:
  beamer_presentation: default
fontsize: 12pt
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(ggplot2)
library(ProbBayes)
library(dplyr)
library(tidyverse)
crcblue <- "#2905a1"
```

## Introduction
 
- In Chapter 3,  the conditional probability of an event $A$ was defined given knowledge of another event $B$.  

- Back to the sampling balls from a box example, suppose one is told that exactly two red balls are sampled, that is $X$ = 2.

- How does that information change the probabilities about the number of white balls $Y$?
 
## A Conditional Calculation

 In this example, one is interested in finding $P(Y = y \mid X = 2)$.  
 
 - Using the definition of conditional probability, one has
$$
 P(Y = y \mid X = 2)  = \frac{P(Y = y, X = 2)}{P(X = 2)}. \\
  = \frac{f(2, y)}{f_X(2)}
 $$
 
## A Conditional Calculation

- For example, the probability of observing two white balls given that we have two red balls is equal to 
$$
 P(Y = 2 \mid X = 2)  = \frac{P(Y = 2, X = 2)}{P(X = 2)} \\
  = \frac{f(2, 2)}{f_X(2)} \\
 = \frac{54 / 252}{105/252} = \frac{54}{105}. \\
$$
 
## A Conditional pmf

- Suppose this calculation is repeated for all possible values of $Y$ -- one obtains the values displayed in this table.
 
 | \(y\) | \(f_{Y \mid X}(y \mid X = 2)\) |
| :---: | :----------------------------: |
|   0   |             3/105              |
|   1   |             36/105             |
|   2   |             54/105             |
|   3   |             12/105             |


- These probabilities represent the conditional pmf for $Y$ conditional on $X = 2$.  

## A Conditional pmf is a Probability Distribution

- This conditional pmf is just like any other probability distribution -- the values are nonnegative and they sum to one. 

- That is ...

1.  $f_{Y \mid X}(y | x) \ge 0$ for all $y$

2.  $\sum_y f_{Y \mid X}(y | x) = 1$

## Conditional pmf Example

- To illustrate using this distribution, suppose one is told that two red balls are selected (that is, $X = 2$) and one wants to find the probability that more than one white ball is chosen.  

- This probability is given by
$$
 P(Y > 1 \mid X = 2)  = \Sigma_{y >1} \, \, f_{Y \mid X}(y \mid X = 2) \\
  = f_{Y \mid X}(2 \mid X = 2) + f_{Y \mid X}(3 \mid X = 2) \\
  = \frac{54}{105} + \frac{12}{105} = \frac{66}{105}.
$$ 
 
## General Formula
 
- In general, the conditional probability mass function of $Y$ conditional on $X = x$, denoted by $f_{Y\ \mid X}(y \mid x)$, is defined to be
$$
 f_{Y \mid X}(y \mid x)  = \frac{f(x, y)}{f_X(x)}, \, \, {\rm if} \, \, f_X(x) > 0.
$$
 
- We can turn this around and find the conditional mass function of $X$ conditional on the value $Y = y$.
$$
 f_{X \mid Y}(x \mid y)  = \frac{f(x, y)}{f_Y(y)}, \, \, {\rm if} \, \, f_Y(y) > 0.
$$
