---
title: "Chapter 6.3b Marginal and Conditional Density Functions"
author: "Jim Albert and Monika Hu"
date: "Chapter 6 Joint Probability Distributions"
output:
  beamer_presentation: default
fontsize: 12pt
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(ggplot2)
library(ProbBayes)
library(dplyr)
library(tidyverse)
crcblue <- "#2905a1"
```

## Marginal probability density functions

- Given a joint pdf $f(x, y)$, one summarizes probabilities about each variable individually by the computation of marginal pdfs.  

- The marginal pdf of $X$, $f_X(x)$, is obtained by integrating out $y$ from the joint pdf.
$$
f_X(x) = \int f(x, y) dy.
$$

- In a similar fashion, one defines the marginal pdf of $Y$ by integrating out $x$ from the joint pdf.
$$
f_Y(x) = \int f(x, y) dx.
$$

## Example

- Let's illustrate the computation of marginal pdfs for our example.  

- Looking back at the figure, one sees that if the value of $x$ is fixed, then the limits for $y$ go from $x$ to 2.  

- So the marginal density of $X$ is given by
$$
 f_X(x)  = \int f(x, y) dy \\
  = \int_x^2  \frac{1}{2}  dy \\
  = \frac{2 - x}{2}, \, \, 0 < x < 2.
$$ 
## Example
 
 - By a similar calculation, one can verify that the marginal density of $Y$ is equal to
 $$
 f_Y(y) = \frac{y}{2}, \, \, 0 < y < 2.
 $$

## Conditional probability density functions

- Once a joint pdf $f(x, y)$ has been defined, one can also define conditional pdfs.  

- In our example, suppose one is told that the first random location is equal to $X = 1.5$.  What has one learned about the value of the second random variable $Y$?

- One defines the notion of a conditional pdf.  The conditional pdf of the random variable $Y$ given the value $X = x$ is defined as the quotient
$$
f_{Y \mid X}(y \mid X = x) = \frac{f(x, y)}{f_X(x)}, \, \, {\rm if} \, \, f_X(x) > 0.
$$

## Conditional density function for example

- In our example one is given that $X = 1.5$.  

- Looking at the figure, one sees that when $X = 1.5$, the only possible values of $Y$ are between 1.5 and 2.  

## Conditional density function for example

- By substituting the values of $f(x, y)$ and $f_X(x)$, one obtains
$$
 f_{Y \mid X}(y \mid X = 1.5)  = \frac{f(1.5, y)}{f_X(1.5)} \\
  =  \frac{1/2}{(2 - 1.5) / 2} \\
  =  2, \, \, 1.5 < y < 2. \\
$$ 

- In other words, the conditional density for $Y$ when $X = 1.5$ is uniform from 1.5 to 2.

## Working with a conditional density function

- A conditional pdf is a legitimate density function, so the integral of the pdf over all values $y$ is equal to one.  

- Use this density to compute conditional probabilities.  

- For example, if $X$ = 1.5, what is the probability that $Y$ is greater than 1.7?  

## Working with a conditional density function

- This probability is the conditional probability $$P(Y > 1.7 \mid X = 1.5)$$ that is given by:
$$
 P(Y > 1.7 \mid X = 1.5)  = \int_{1.7}^2 f_{Y \mid X}(y \mid 1.5) dy \\
  =  \int_{1.7}^2 2 dy \\
  =  0.6. \\
$$
 
## Turn the random variables around   

- Above, we looked at the  pdf of $Y$ conditional on a value of $X$. 

- One can also consider a pdf of $X$ conditional on a value of $Y$.  

- Returning to our example, suppose that one learns that $Y$, the larger random variable on the interval is equal to 0.8.  In this case, what would one expect for the random variable $X$?

- This question is answered in two steps -- one first finds the conditional pdf of $X$ conditional on $Y = 0.8$.  Then once this conditional pdf is found, one finds the mean of this distribution.

## The conditional pdf of $X$ given $Y = y$

- The conditional pdf of $X$ given the value $Y = y$ is defined as the quotient
$$
f_{X \mid Y}(x \mid Y = y) = \frac{f(x, y)}{f_Y(y)}, \, \, {\rm if} \, \, f_Y(y) > 0.
$$

- Looking back the figure, one sees that if $Y = 0.8$, the possible values of $X$ are from 0 to 0.8.  

- Over these values the conditional pdf of $X$ is given by
$$
 f_{X \mid Y}(x \mid 0.8)  = \frac{f(x, 0.8)}{f_Y(0.8)} \\
  =  \frac{1/2}{0.8 / 2} 
  =  1.25, \, \, 0 < x < 0.8. \\
$$ 
 
## Continuing
 
 - So if one knows that $Y = 0.8$, then the conditional pdf for $X$ is Uniform on (0, 0.8).
 
 - To find the "expected" value of $X$ knowing that $Y = 0.8$, one finds the mean of this distribution.
 $$
 E(X \mid Y = 0.8)  = \int_0^{0.8} x f_{X \mid Y}(x \mid 0.8) dx \\
  = \int_0^{0.8} x \,1.25 \, dx \\ \\
  =  (0.8)^2 / 2 \times 1.25 = 0.4. \\
$$
