---
title: Chapter 2.7 Playing Yahtzee
author: Jim Albert and Monika Hu
date: Chapter 2 Counting Methods
output: 
  beamer_presentation: default
fontsize: 12pt
---

## Introduction

- Yahtzee is a popular game played with five dice.  
- The game is similar to the card game poker -- in both games, one is trying to achieve desirable patterns in the dice faces or cards.

- Some of the dice patterns in the first roll in Yahtzee are described .

- The problem of determining the chances of several of the patterns are considered.

## Outcomes of one roll of five dice

- When a player rolls five dice in the game Yahtzee, the most valuable result is when all of the five dice show the same number such as

\begin{center}
2, 2, 2, 2, 2.
\end{center}

- This is called a "Yahtzee" and the player scores 50 points with this pattern.  

- A second valuable pattern is a "four-of-a-kind' where you observe one number appearing four times, such as

3, 4, 3, 3, 3.

## Table gives all of the possible patterns when you roll five dice in Yahtzee.  


| Pattern         | Sample of pattern | Point value |
| :-------------- | :---------------: | :---------: |
| Yahtzee         |   4, 4, 4, 4, 4   |     50      |
| Four-of-a-kind  |   6, 6, 6, 4, 6   |             |
| Large straight  |   2, 6, 4, 5, 3   |     40      |
| Small straight  |   4, 2, 1, 3, 2   |     30      |
| Full house      |   5, 1, 1, 5, 1   |     25      |
| Three-of-a-kind |   2, 2, 3, 4, 2   |             |
| Two pair        |   6, 3, 3, 6, 2   |             |
| One pair        |   4, 3, 4, 1, 5   |             |
| Nothing         |   1, 3, 2, 5, 6   |             |

## Total number of outcomes


- It is useful to distinguish the five dice when one counts outcomes.  

- One can represent an outcome by placing a value of individual die rolls (1 through 6) in the six slots.

|                                 |                                 |                                 |                                 |                                 |
| :-----------------------------: | :-----------------------------: | :-----------------------------: | :-----------------------------: | :-----------------------------: |
| <span class="underline"></span> | <span class="underline"></span> | <span class="underline"></span> | <span class="underline"></span> | <span class="underline"></span> |
|              die 1              |              die 2              |              die 3              |              die 4              |              die 5              |

- So two possible outcomes are 

2, 3, 4, 5, 5 and 3, 2, 4, 5, 5.

## Number of outcomes

- Each die has 6 possibilities and so, applying the multiplication rule\index{multiplication rule!counting}, the total number of outcomes in the rolls of five dice is
$$
6 \times  6\times   6\times   6\times   6 = 7776.
$$

- Since all of the outcomes are equally likely\index{equally likely}, we assign a probability of 1/7776 to each outcome. 
 
## Probability of a Yahtzee

- One represents the Yahtzee roll as the outcome
$$
x, x, x, x, x
$$
where $x$ denotes a roll of one die.  There are six possible choices for $x$, and so the number of possible Yahtzees is 6.

- Since each outcome has probability 1/7776, the probability of a Yahtzee is
$$
Prob({\rm Yahtzee}) = \frac{6}{7776}.
$$

## Probability of four-of-a-kind

- In the pattern "four of a kind", one wants to have one number appear four times and a second number appear once.  

- One is interested in counting outcomes of the form
$$
x, x, x, x, y
$$
where the four $x$'s and the single $y$ can be in different orders.

## Representation of 4-of-a-kind

- To apply the multiplication rule,  think of writing down a possible "four-of-a-kind" in three steps.  

- Step 1:  Choose the number for $x$ (the number that appears four times).
- Step 2:  Next choose the number for the singleton $y$.
- Step 3:  Mix up the orders of the four $x$'s and the one $y$.

- For example, one chooses the outcome 5, 5, 5, 3, 5 by (1) choosing 5 to be the number that appears four times, (2) choosing 3 as the number that appears once, and then arranging the digits 5, 5, 5, 5, 3 to get 5, 5, 5, 3, 5.

## Counting outcomes

- Step 1:  There are 6 ways of choosing $x$.  
- Step 2:  Once $x$ has been chosen, there are 5 ways of choosing the value for $y$. 
- Step 3:  Last, once $x$ and $y$ have been selected, there are  ${5 \choose 4}  = 5$  ways of mixing up the $x$'s and $y$'s.  

- Apply the multiplication rule:

Number of ways = $6 \times  5 \times  5 = 150$.

- The corresponding probability of four-of-a-kind is
$$
Prob({\rm four-}{\rm of-}{\rm a-}{\rm kind}) = \frac{150}{7776}.
$$






