---
title: Chapter 2.2 Equally Likely Outcomes
author: Jim Albert and Monika Hu
date: Chapter 2 Counting Methods
output: 
  beamer_presentation: default
fontsize: 12pt
---

## Introduction

- Assume one writes the sample space\index{sample!space} in such a way that the outcomes are equally likely.  

- Applying the classical interpretation\index{classical view of probability}, the probability of each outcome will be

\begin{equation}
Prob({\rm Outcome}) = \frac{1}{{\rm Number} \, {\rm of} \, {\rm outcomes}}.
\end{equation}

- If one is interested in the probability of some event, then the probability is given by 
\begin{equation}
Prob({\rm Event}) = \frac{{\rm Number} \, {\rm of} \, {\rm outcomes} \, {\rm in} \,
{\rm event}}{{\rm Number} \, {\rm of} \, {\rm outcomes}}.
\end{equation}

## An example

- To illustrate the use (and misuse) of this formula, suppose one has a box containing five balls of which three are red, one is blue, and one is white.  

- One selects three balls without replacement\index{without replacement} from the box -- what is the probability that  all red balls are chosen?
  
- Let's consider two representations of the sample space of this experiment.

## Sample space 1:

- Suppose one does not distinguish between balls of the same color and does not care about the order in which the balls are selected.  

- Then if $R$, $B$, $W$ denote choosing a red, blue, and white ball respectively, then there are four possible outcomes:
$$
S_1 = \{(R, R, R), (R, R, B), (R, R, W), (R, B, W)\}.
$$

- If these outcomes in $S_1$ are assumed equally likely, then the probability of choosing all red balls is
$$
Prob({\rm all} \,  {\rm reds}) = \frac{1}{4}.
$$

## Sample space 2

- Suppose instead that one distinguishes the balls of the same color, so the balls in the box are denoted by $R1, R2, R3, B, W$.  

- Then one writes down ten possible outcomes

$S_2$ = \{$(R1, R2, R3)$, $(R1, R2, B)$, $(R1, R2, W)$, $(R1, R3, B)$, $(R1, R3, W)$, $(R2, R3, B)$, $(R2, R3, W)$, $(R1, B, W)$, $(R2, B, W)$, $(R3, B, W)$\}.

- If one assumes these outcomes are equally likely, then the probability of choosing all reds is
$$
Prob({\rm all} \,  {\rm reds}) = \frac{1}{10}.
$$

## Two different answers?

- The problem is that the outcomes in the first sample space $S_1$ are not equally likely.  

- The chance of choosing three reds $(R, R, R)$ is smaller than the chance of choosing a red, blue and white $(R, B, W)$ 

- There is only one way of selecting three reds, but there are three ways of selecting exactly one red.  

- The outcomes in sample space $S_2$ are equally likely since the balls were distinguished and it is reasonable that any three of the five balls has the same chance of being selected.

## What have we learned?

- When one writes down a sample space, one should think carefully about the assumption that outcomes are equally likely.  

- When one has an experiment with duplicate items (like three red balls), it may be preferable to distinguish the items when one writes down the sample space and computes probabilities. 


