---
title: Chapter 1.6 Assigning Probabilities
author: Jim Albert and Monika Hu
date: Chapter 1 Probability, A Measure of Uncertainty
output: 
  beamer_presentation: default
fontsize: 12pt
---

## Example - Choosing an Ice Cream Flavor

- To illustrate different assignments of probabilities, suppose a school girl goes to an ice cream parlor and plans to order a single-dip ice cream cone.  This  parlor has four different ice cream flavors.  Which flavor will the school girl order?  

- First, one writes down the sample space -- the possible flavors that the school girl can order.  

Flavor  | Vanilla |  Chocolate| Butter Pecan |Maple Walnut
----|----|----|----|----
Probability | | | |

## Basic Facts About Probabilities

Here are some basic facts  about probabilities:  

- Any probability that is assigned must fall between 0 and 1  
- The sum of the probabilities across all outcomes must be equal to 1.
- An outcome will be assigned a probability of 0 if one is sure that that outcome will never occur.  
- Likewise, if one assigns a probability of 1 to an event, then that event must occur all the time.  

## Scenario 1

 Schoolgirl has brought a hat in which she has placed many slips of paper -- 10 slips are labeled "vanilla", 10 slips are labeled "chocolate", and 10 slips are "butter pecan", and 10 are "maple walnut".  She makes her ice cream choice by choosing a slip at random.

Flavor  | Vanilla |  Chocolate| Butter Pecan |Maple Walnut
----|----|----|----|----
Probability |1/4 |1/4 |1/4 |1/4

## Scenario 2

Let's consider a different set of probabilities based on different assumptions.  A person knows that she really doesn't like "plain" flavors like vanilla or chocolate, and she really likes ice creams with nut flavors.  

Flavor  | Vanilla |  Chocolate| Butter Pecan |Maple Walnut
----|----|----|----|----
Probability |0 |0 |0.7 |0.3

## Scenario 3

The worker at the ice cream shop has no idea what flavor the school girl will order.  But the worker has kept a record of how many cones of each type have been ordered -- of 50 cones ordered, 10 are vanilla, 14 are chocolate, 20 are butter pecan, and 6 are maple walnut. She believes that the school girl has similar tastes to the previous customers.

Flavor  | Vanilla |  Chocolate| Butter Pecan |Maple Walnut
----|----|----|----|----
Probability |10/50 |14/50 |20/50 |6/50

## Comments

- Each of the  probability assignments used a different viewpoint of probability as described in previous sections.  

- The first assignment used the classical viewpoint using equally likely outcomes.

- The second assignment was an illustration of the subjective view where one's assignment was based on one's opinion about the favorite flavors of one's daughter.  

- The last assignment was based on the frequency viewpoint\index{frequency view of probability} where the probabilities were estimated from the observed flavor preferences of 50 previous customers.  


