---
title: Chapter 11.5 Posterior Analysis
author: Jim Albert and Monika Hu
date: Chapter 11 Simple Linear Regression
output: 
    beamer_presentation: default
    logo: ProbBayes_cover.jpg
fontsize: 12pt
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(ggplot2)
library(ProbBayes)
library(dplyr)
library(runjags)
library(coda)
library(tidyverse)
crcblue <- "#2905a1"
```

## The linear regression model and priors
- Sampling model:
\begin{equation}
Y_i \mid \mu_i, \sigma \overset{ind}{\sim} \textrm{Normal}(\mu_i, \sigma)
\end{equation}

- Weakly informative priors:
\begin{eqnarray}
\beta_0 &\sim& \textrm{Normal}(\mu_0, s_0) \\
\beta_1 &\sim& \textrm{Normal}(\mu_1, s_1)
\end{eqnarray}

\begin{equation}
\phi = 1/\sigma^2 \sim \textrm{Gamma}(1, 1)
\end{equation}

## The likelihood function
- The likelihood is the joint density of these observations viewed as a function of $(\beta_0, \beta_1, \sigma)$  
- For convenience, the standard deviation $\sigma$ is reexpressed as the precision $\phi = 1 / \sigma^2$ (Chapter 8)

\begin{eqnarray}
L(\beta_0, \beta_1, \phi) &= & \prod_{i=1}^n \left[\frac{\sqrt{\phi}}{\sqrt{2 \pi}}
\exp\left\{-\frac{\phi}{2}(y_i - \beta_0 - \beta_1 x_i)^2\right\}\right]
 \nonumber \\
& \propto & \phi^{\frac{n}{2}} \exp\left\{-\frac{\phi}{2}\sum_{i=1}^n (y_i - \beta_0 - \beta_1 x_i)^2\right\} 
\end{eqnarray}

## The joint posterior

- By multiplying the likelihood by the prior for $(\beta_0, \beta_1, \phi)$, one obtains an expression for the posterior density

\pause

\begin{eqnarray}
\pi(\beta_0, \beta_1, \phi \mid y_1, \cdots, y_n) &\propto & \phi^{\frac{n}{2}} \exp\left\{-\frac{\phi}{2}\sum_{i=1}^n (y_i - \beta_0 - \beta_1 x_i)^2\right\} \nonumber \\
 & \times & \exp\left\{-\frac{1}{2 s_0^2}(\beta_0 - \mu_0)^2\right\} \nonumber \\
 & & \exp\left\{-\frac{1}{2 s_1^2}(\beta_1 - \mu_1)^2\right\} \nonumber \\ 
& \times & \phi^{a-1} \exp(-b \phi) 
\end{eqnarray}



## The joint posterior cont'd

- Since this is not a familiar probability distribution, one needs to use an MCMC algorithm to obtain simulated draws from the posterior

- We will use JAGS
