---
title: Chapter 3.4 In a Two-Way Table
author: Jim Albert and Monika Hu
date: Chapter 3 Conditional Probability
output: 
  beamer_presentation: default
fontsize: 12pt
---

## Two-way table

- It can be easier to think about, and compute conditional probabilities when they are found from observed counts in a two-way table.

- In the table on the next slide,  high school athletes in 14 sports are classified with respect to their sport and their gender.  

- These numbers are recorded in thousands, so the 454 entry in the Baseball/Softball -- Male cell means that 454,000 males played baseball or softball this year.

## The table

|                   | Male | Female | TOTAL |
| :---------------- | :--: | :----: | :---: |
| Baseball/Softball | 454  |  373   |  827  |
| Basketball        | 541  |  456   |  997  |
| Cross Country     | 192  |  163   |  355  |
| Football          | 1048 |   1    | 1049  |
| Gymnastics        |  2   |   21   |  23   |
| Golf              | 163  |   62   |  225  |
| Ice Hockey        |  35  |   7    |  42   |
| Lacrosse          |  50  |   39   |  89   |
| Soccer            | 345  |  301   |  646  |
| Swimming          |  95  |  141   |  236  |
| Tennis            | 145  |  163   |  308  |
| Track and Field   | 550  |  462   | 1012  |
| Volleyball        |  39  |  397   |  436  |
| Wrestling         | 240  |   4    |  244  |
| TOTAL             | 3899 |  2590  | 6489  |


## Some events

Suppose one chooses a high school athlete at random.  Consider several events

- $F$ = athlete chosen is female
- $S$ = athlete is a swimmer
- $V$ = athlete plays volleyball

## Computing some probabilities

- What is the probability that the athlete is female?

- Of the 6489 (thousand) athletes, 2590 were female, so the probability is

$P(F)$ = 2590/6489 = 0.3991


- Likewise, the probability that the randomly chosen athlete is a swimmer is

$P(S)$ = 236/6489 = 0.0364.

- The probability he or she plays volleyball is

$P(V)$ = 436/6489 = 0.0672.


## Some conditional probabilities

- What is the probability a volleyball player is female?  We want to find 

$$P(F \mid V).$$

- Restrict attention only to the volleyball players

|            | Male | Female | TOTAL |
| :--------- | :--: | :----: | :---: |
| Volleyball |  39  |  397   |  436  |

- Of the 436 (thousand) volleyball players, 397 are female, so

$$P(F \mid V) = 397/436 = 0.9106.$$

## Another conditional probability

- What is the probability a woman athlete is a swimmer?  We want to find $P(S \mid F)$

- One restricts attention to the "Female" column of counts.  There are a total of 2590 (thousand) women who play one of these sports; of these, 141 are swimmers.  So

$$
P(S \mid F) = 141/2590 = 0.0544.
$$

## Independent events?

- Are events $F$ and $V$ independent?  

- Above it was found that the probability a randomly chosen athlete is a volleyball player is $P(V)$ = 0.0672.  

- Next one finds the probability $P(V \mid F)$.
Of the 2590 women, 397 are volleyball players, and so $P(V \mid F)$ = 397/2590 = 0.1533,   

- Note that the knowledge the athlete is female has increased one's probability that the athlete is a volleyball player.  So the two events are not independent.


