---
title: Chapter 3.3 In Everyday Life
author: Jim Albert and Monika Hu
date: Chapter 3 Conditional Probability
output: 
  beamer_presentation: default
fontsize: 12pt
---

## Introduction

- Generally one's beliefs about uncertain events can change when new information is obtained.

- Conditional probability provides a way to precisely say how one's beliefs change.  

## Estimating the population of Philadelphia

- One is interested in estimating the population\index{population} of Philadelphia, Pennsylvania in the current year.  

- Consider three possible events:


- $A$ = Philadelphia's population is under one million
- $B$ = Philadelphia's population is between one and two million
- $C$ = Philadelphia's population is over two million

## Initial beliefs

- If one knows little about Philadelphia, then one probably are not very knowledgeable about its population.  

- So initially the probabilities are assigned shown in the following table

| Event                       | \(P(Event \mid I)\) |
| :-------------------------- | :-----------------: |
| under one million           |         0.3         |
| between one and two million |         0.3         |
| over two million            |         0.4         |
| TOTAL                       |         1.0         |



- One assigns approximately the same probability to each of the three events, indicating that they are all equally likely in one's mind.  

## New information

- Now the person is told that in 1990, Philadelphia was the fifth largest city in the country, and the population of the sixth largest city, San Diego, was 1.1 million in 1990.  

So one thinks that 

-	 The population of Philadelphia is most likely to be between 1 and 2 million.
-	 It is very unlikely that Philadelphia's population is over 2 million.
- There is a small chance that Philadelphia's population is under 1 million.

## New probabilities

- One then revise his or her probabilities that reflect these beliefs as shown in the table below.  

- These  probabilities are denoted as $P(Event \mid N)$, which are probabilities of these population events conditional on the newer information $N$.


| Event                       | \(P(Event \mid N)\) |
| :-------------------------- | :-----------------: |
| under one million           |         0.2         |
| between one and two million |        0.78         |
| over two million            |        0.02         |
| TOTAL                       |         1.0         |

## Additional information

- One looks up the Census estimated figures and the population of Philly was reported to be 1,567,872 in 2016.  

- Even though the Census number is a few years old, one doesn't think that the population has changed much.  

- So one's probabilities will change again as shown in the table.  We call these probabilities of events conditional on additional information $A$.


| Event                       | \(P(Event \mid A)\) |
| :-------------------------- | :-----------------: |
| under one million           |          0          |
| between one and two million |          1          |
| over two million            |          0          |
| TOTAL                       |         1.0         |

## Making judgements under uncertainty

- For example, we make decisions about the weather based on information such as the weather report, how it looks outside, and advice from friends.  

- We make decisions about who we think will win a sports event based on what we read in the paper, our knowledge of the teams' strengths, and discussion with friends.  

- Conditional probability is simply a way of quantifying our beliefs about uncertain events given information. 
