---
title: Chapter 8.2 Modeling Measurements
author: Jim Albert and Monika Hu
date: Chapter 8 Modeling Measurement and Count Data
output:
  beamer_presentation: default
fontsize: 12pt
---

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(ggplot2)
library(ProbBayes)
library(dplyr)
library(tidyverse)
crcblue <- "#2905a1"
```

## Introduction

- Assume we have hypothetical population of individuals of interest.

- There is a continuous-valued measurement $Y$ associated with each individual.
- Represent the collection of measurements from all individuals by means of a continuous probability density $f(y)$.

- The mean value $\mu$ is a typical value of the continuous measurement $Y$.

## Sampling

- A random sample of individuals $Y_1, ..., Y_n$ will be taken.  

- Also have prior beliefs about location of $\mu$.

- The inferential problem is to use these  measurements together with any prior beliefs to learn about the population mean $\mu$.  

## College applications 

- How many college applications does a high school senior in the United States complete?  

- Imagine a population of all American high school seniors and the measurement is the number of completed college applications

- The unknown quantity is the mean number of  applications $\mu$ completed by these high school seniors

- Conduct a survey to a sample of high school seniors  and use information from the survey to perform  inference about the mean number of college applications.

## Household spending {-}

- How much does a household in San Francisco spend on housing every month?  

- Consider the population of households in San Francisco and the continuous measurement is the amount of money spent on housing . 
 
- To learn about the mean value of housing $\mu$ of all San Francisco residents,  a  sample survey is  conducted.  

- The mean value of the housing costs $\bar y$ from this sample of surveyed households is informative about the mean housing cost  $\mu$ for all residents.

## The general approach

Recall the three general steps of Bayesian inference in the context of an unknown proportion $p$.

- Step 1: **Prior** We express an opinion about the location of the proportion $p$ before sampling\index{sampling}.

- Step 2: **Data/Likelihood** We take the sample and record the observed proportion.

- Step 3: **Posterior** We use Bayes' rule\index{Bayes' rule} to sharpen and update the previous opinion about $p$ given the information from the sample.

## Normal population

- Have a continuous population of measurements 
represented by  $Y$ with density function\index{density!function} $f(y)$.  

- Assume that this population has a Normal\index{Normal} shape with mean $\mu$ and standard deviation $\sigma$.  

- Single measurement $Y$ is assume to come from the density function

$$
f(y) = \frac{1}{\sqrt{2 \pi} \sigma} \exp\left\{- \frac{(y - \mu)^2}{2 \sigma^2}\right\}, -\infty < y< \infty.
$$

- Assume that the standard deviation $\sigma$ of the measurement distribution is known and the objective is to learn about the single mean measurement $\mu$.

## Prior

- Step 1 in Bayesian inference is to express an opinion about the parameter.  

- One constructs a prior for the mean parameter $\mu$ that expresses one's opinion about the location of this mean.

- One attractive discrete approach for expressing this prior opinion constructs a list of possible values of $\mu$, and then one assigns probabilities to the possible values to reflect one's belief.  

- Alternatively, one can use of a continuous prior to represent one's belief for $\mu$.  

## Data

- Step 2 of our process is to collect measurements from a random sample.

- In our first situation, one collects the number of applications from a sample of 100 high school seniors.  

- If  measurements  are viewed as independent observations from a Normal sampling density with mean $\mu$,  then one  constructs a likelihood function which is the joint density of the sampled measurements viewed as a function of the unknown parameter.  

## Update opinion

- Step 3 applies Bayes' rule to update one's prior opinion to obtain a posterior distribution for the mean $\mu$.  

- The algebraic implementation of Bayes' rule  is a bit more tedious when dealing with continuous data with a Normal sampling density.  

- But we will see there is a simple procedure for computing the posterior mean\index{posterior!mean} and standard deviation.





